/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange credentials for an access token */
        post: operations["AuthController_login_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user profile + permissions */
        get: operations["AuthController_me_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the authenticated user password */
        post: operations["AuthController_changePassword_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users with search, filters and pagination */
        get: operations["UsersController_list_v1"];
        put?: never;
        /** Create a new user */
        post: operations["UsersController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user by id */
        get: operations["UsersController_get_v1"];
        put?: never;
        post?: never;
        /** Delete a user */
        delete: operations["UsersController_remove_v1"];
        options?: never;
        head?: never;
        /** Update a user */
        patch: operations["UsersController_update_v1"];
        trace?: never;
    };
    "/api/v1/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the permission catalog grouped by domain */
        get: operations["PermissionsController_catalog_v1"];
        put?: never;
        /** Create a new permission in the catalog */
        post: operations["PermissionsController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/permissions/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a permission (blocked if granted) */
        delete: operations["PermissionsController_remove_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/permissions/roles/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the permission keys granted to a role */
        get: operations["PermissionsController_grants_v1"];
        /** Replace the permission set granted to a role */
        put: operations["PermissionsController_replaceGrants_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List roles with user counts */
        get: operations["RolesController_list_v1"];
        put?: never;
        /** Create a role */
        post: operations["RolesController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a role by id */
        get: operations["RolesController_get_v1"];
        put?: never;
        post?: never;
        /** Delete a role (blocked if assigned) */
        delete: operations["RolesController_remove_v1"];
        options?: never;
        head?: never;
        /** Edit a role description */
        patch: operations["RolesController_update_v1"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponseDto: {
            /**
             * @example ok
             * @enum {string}
             */
            status: "ok" | "error";
            /** @example 2026-09-14T10:00:00.000Z */
            timestamp: string;
            /** @example 1234.56 */
            uptime: number;
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "latencyMs": 3
             *       }
             *     }
             */
            dependencies: Record<string, never>;
        };
        LoginDto: {
            /** @example owner@delivery.local */
            email: string;
            /** @example owner1234 */
            password: string;
        };
        /** @enum {string} */
        UserStatus: "ACTIVE" | "INACTIVE";
        UserResponseDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            id: string;
            /** @example System Owner */
            name: string;
            /** @example owner@delivery.local */
            email: string;
            /** @example 09123456789 */
            phone: Record<string, never> | null;
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            roleId: string;
            /** @example OWNER */
            role: string;
            /** @example ACTIVE */
            status: components["schemas"]["UserStatus"];
            /** @example 2026-09-14T10:00:00.000Z */
            createdAt: string;
            /** @example 2026-09-14T10:00:00.000Z */
            updatedAt: string;
        };
        LoginResponseDto: {
            /** @description JWT access token */
            accessToken: string;
            /** @description Authenticated user */
            user: components["schemas"]["UserResponseDto"];
            /** @description Effective permission keys for the user role */
            permissions: string[];
        };
        MeResponseDto: {
            /** @description Authenticated user profile */
            user: components["schemas"]["UserResponseDto"];
            /** @description Effective permission keys for the user role */
            permissions: string[];
        };
        ChangePasswordDto: {
            currentPassword: string;
            newPassword: string;
        };
        PaginationMetaDto: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            perPage: number;
            /** @example 42 */
            total: number;
            /** @example 3 */
            totalPages: number;
        };
        UserListResponseDto: {
            data: components["schemas"]["UserResponseDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        CreateUserDto: {
            /** @example John Rider */
            name: string;
            /** @example john@delivery.local */
            email: string;
            /** @example 09123456789 */
            phone?: Record<string, never> | null;
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            roleId: string;
            /** @example StrongP@ssw0rd */
            password: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
        };
        UpdateUserDto: {
            /** @example John Rider Updated */
            name?: string;
            /** @example john.updated@delivery.local */
            email?: string;
            /** @example 09876543210 */
            phone?: Record<string, never> | null;
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            roleId?: string;
            status?: components["schemas"]["UserStatus"];
            /** @description Reset user password (min 8 characters) */
            password?: string;
        };
        PermissionGroupDto: {
            /** @example users */
            domain: string;
            /**
             * @example [
             *       "users.list",
             *       "users.read"
             *     ]
             */
            permissions: string[];
        };
        CreatedPermissionDto: {
            /** @example shops.manage */
            name: string;
            /** @example shops */
            domain: string;
        };
        RoleResponseDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            id: string;
            /** @example MANAGER */
            name: string;
            /** @example Floor manager */
            description: Record<string, never> | null;
            /** @example false */
            isSystem: boolean;
            /** @example 3 */
            userCount: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
        };
    };
    AuthController_login_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    AuthController_me_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponseDto"];
                };
            };
        };
    };
    AuthController_changePassword_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_list_v1: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
                /** @description Search by name, email or phone */
                search?: string;
                /** @description Filter by role id */
                roleId?: string;
                status?: components["schemas"]["UserStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponseDto"];
                };
            };
        };
    };
    UsersController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UsersController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UsersController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    PermissionsController_catalog_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionGroupDto"][];
                };
            };
        };
    };
    PermissionsController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedPermissionDto"];
                };
            };
        };
    };
    PermissionsController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PermissionsController_grants_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Granted permission keys */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PermissionsController_replaceGrants_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The granted keys after the update */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponseDto"][];
                };
            };
        };
    };
    RolesController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created role */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponseDto"];
                };
            };
        };
    };
    RolesController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated role id */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
