/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange credentials for an access token */
        post: operations["AuthController_login_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user profile + permissions */
        get: operations["AuthController_me_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the authenticated user password */
        post: operations["AuthController_changePassword_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users with search, filters and pagination */
        get: operations["UsersController_list_v1"];
        put?: never;
        /** Create a new user */
        post: operations["UsersController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user by id */
        get: operations["UsersController_get_v1"];
        put?: never;
        post?: never;
        /** Delete a user */
        delete: operations["UsersController_remove_v1"];
        options?: never;
        head?: never;
        /** Update a user */
        patch: operations["UsersController_update_v1"];
        trace?: never;
    };
    "/api/v1/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the fixed permission catalog grouped by module */
        get: operations["PermissionsController_catalog_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/permissions/roles/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the permission keys granted to a role */
        get: operations["PermissionsController_grants_v1"];
        /** Replace the permission set granted to a role */
        put: operations["PermissionsController_replaceGrants_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List roles with user counts */
        get: operations["RolesController_list_v1"];
        put?: never;
        /** Create a role */
        post: operations["RolesController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a role by id */
        get: operations["RolesController_get_v1"];
        put?: never;
        post?: never;
        /** Delete a role (blocked if assigned) */
        delete: operations["RolesController_remove_v1"];
        options?: never;
        head?: never;
        /** Edit a role description */
        patch: operations["RolesController_update_v1"];
        trace?: never;
    };
    "/api/v1/shops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List shops with search and pagination */
        get: operations["ShopsController_list_v1"];
        put?: never;
        /** Create a shop */
        post: operations["ShopsController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shops/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a shop by id */
        get: operations["ShopsController_get_v1"];
        put?: never;
        post?: never;
        /** Delete a shop */
        delete: operations["ShopsController_remove_v1"];
        options?: never;
        head?: never;
        /** Update a shop */
        patch: operations["ShopsController_update_v1"];
        trace?: never;
    };
    "/api/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List customers with search and pagination */
        get: operations["CustomersController_list_v1"];
        put?: never;
        /** Create a customer */
        post: operations["CustomersController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a customer by id */
        get: operations["CustomersController_get_v1"];
        put?: never;
        post?: never;
        /** Delete a customer */
        delete: operations["CustomersController_remove_v1"];
        options?: never;
        head?: never;
        /** Update a customer */
        patch: operations["CustomersController_update_v1"];
        trace?: never;
    };
    "/api/v1/riders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List riders with search, filters and pagination */
        get: operations["RidersController_list_v1"];
        put?: never;
        /** Create a rider and its login account */
        post: operations["RidersController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/riders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a rider by id */
        get: operations["RidersController_get_v1"];
        put?: never;
        post?: never;
        /** Delete a rider and its login account */
        delete: operations["RidersController_remove_v1"];
        options?: never;
        head?: never;
        /** Update a rider and its login account */
        patch: operations["RidersController_update_v1"];
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List orders with filters and pagination */
        get: operations["OrdersController_list_v1"];
        put?: never;
        /** Register an office-received order and assign a rider by township rotation */
        post: operations["OrdersController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an order status history */
        get: operations["OrdersController_history_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an order by id with its history */
        get: operations["OrdersController_get_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/townships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TownshipsController_list_v1"];
        put?: never;
        post: operations["TownshipsController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/townships/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["TownshipsController_update_v1"];
        trace?: never;
    };
    "/api/v1/deliveries/{orderId}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DeliveriesController_assign_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deliveries/{id}/reassign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["DeliveriesController_reassign_v1"];
        trace?: never;
    };
    "/api/v1/deliveries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DeliveriesController_get_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deliveries/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DeliveriesController_complete_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/deliveries/{id}/fail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DeliveriesController_fail_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{orderId}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrdersDeliveriesController_list_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{orderId}/deliveries/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OrdersDeliveriesController_retry_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/riders/me/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RiderDeliveriesController_list_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rider/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RiderBoardController_board_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rider/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RiderBoardController_dashboard_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/office/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get read-only office operational dashboard aggregates */
        get: operations["OfficeDashboardController_getDashboard_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponseDto: {
            /**
             * @example ok
             * @enum {string}
             */
            status: "ok" | "error";
            /** @example 2026-09-14T10:00:00.000Z */
            timestamp: string;
            /** @example 1234.56 */
            uptime: number;
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "latencyMs": 3
             *       }
             *     }
             */
            dependencies: Record<string, never>;
        };
        LoginDto: {
            /** @example owner@mail.com */
            email: string;
            /** @example Password1234 */
            password: string;
        };
        /** @enum {string} */
        UserStatus: "ACTIVE" | "INACTIVE";
        UserResponseDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            id: string;
            /** @example System Owner */
            name: string;
            /** @example owner@mail.com */
            email: string;
            /** @example 09123456789 */
            phone: Record<string, never> | null;
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            roleId: string;
            /** @example OWNER */
            role: string;
            /** @example ACTIVE */
            status: components["schemas"]["UserStatus"];
            /** @example 2026-09-14T10:00:00.000Z */
            createdAt: string;
            /** @example 2026-09-14T10:00:00.000Z */
            updatedAt: string;
        };
        LoginResponseDto: {
            /** @description JWT access token */
            accessToken: string;
            /** @description Authenticated user */
            user: components["schemas"]["UserResponseDto"];
            /** @description Effective permission keys for the user role */
            permissions: string[];
        };
        MeResponseDto: {
            /** @description Authenticated user profile */
            user: components["schemas"]["UserResponseDto"];
            /** @description Effective permission keys for the user role */
            permissions: string[];
        };
        ChangePasswordDto: {
            currentPassword: string;
            newPassword: string;
        };
        PaginationMetaDto: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            perPage: number;
            /** @example 42 */
            total: number;
            /** @example 3 */
            totalPages: number;
        };
        UserListResponseDto: {
            data: components["schemas"]["UserResponseDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        CreateUserDto: {
            /** @example John Rider */
            name: string;
            /** @example john@delivery.local */
            email: string;
            /** @example 09123456789 */
            phone?: Record<string, never> | null;
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            roleId: string;
            /** @example StrongP@ssw0rd */
            password: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
        };
        UpdateUserDto: {
            /** @example John Rider Updated */
            name?: string;
            /** @example john.updated@delivery.local */
            email?: string;
            /** @example 09876543210 */
            phone?: Record<string, never> | null;
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            roleId?: string;
            status?: components["schemas"]["UserStatus"];
            /** @description Reset user password (min 8 characters) */
            password?: string;
        };
        PermissionGroupDto: {
            /** @example users */
            module: string;
            /**
             * @example [
             *       "users.create",
             *       "users.read"
             *     ]
             */
            permissions: string[];
        };
        UpdateRolePermissionsDto: {
            /**
             * @description Permission keys to grant (replaces the set)
             * @example [
             *       "users.create",
             *       "users.read"
             *     ]
             */
            permissions: string[];
        };
        RoleResponseDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            id: string;
            /** @example MANAGER */
            name: string;
            /** @example Floor manager */
            description: Record<string, never> | null;
            /** @example false */
            isSystem: boolean;
            /** @example 3 */
            userCount: number;
        };
        CreateRoleDto: {
            /**
             * @description Uppercase role name, 2-32 chars, letters/digits/underscore
             * @example MANAGER
             */
            name: string;
            /** @example Operations manager */
            description?: Record<string, never>;
        };
        CreateRoleResponseDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            id: string;
            /** @example MANAGER */
            name: string;
            /** @example false */
            isSystem: boolean;
        };
        UpdateRoleDto: {
            /** @example Operations manager */
            description?: Record<string, never>;
        };
        UpdateRoleResponseDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            id: string;
        };
        /** @enum {string} */
        ShopChannelType: "VIBER" | "TELEGRAM";
        ShopResponseDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            id: string;
            /** @example Yangon Central Shop */
            name: string;
            /** @example 09123456789 */
            phone?: Record<string, never> | null;
            /** @example No. 1, Main Road */
            address?: Record<string, never> | null;
            /** @example Deliver before 6pm */
            notes?: Record<string, never> | null;
            /** @example VIBER */
            channelType: components["schemas"]["ShopChannelType"];
            /** @example YangonCentralShop */
            channelName: string;
            /** @example 2026-09-18T10:00:00.000Z */
            createdAt: string;
            /** @example 2026-09-18T10:00:00.000Z */
            updatedAt: string;
        };
        ShopListMetaDto: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            perPage: number;
            /** @example 1 */
            total: number;
            /** @example 1 */
            totalPages: number;
        };
        ShopListResponseDto: {
            data: components["schemas"]["ShopResponseDto"][];
            meta: components["schemas"]["ShopListMetaDto"];
        };
        CreateShopDto: {
            /** @example Yangon Central Shop */
            name: string;
            /** @example 09123456789 */
            phone?: Record<string, never> | null;
            /** @example No. 1, Main Road */
            address?: Record<string, never> | null;
            /** @example Deliver before 6pm */
            notes?: Record<string, never>;
            /** @example VIBER */
            channelType: components["schemas"]["ShopChannelType"];
            /** @example YangonCentralShop */
            channelName: string;
        };
        UpdateShopDto: {
            /** @example Yangon Central Shop */
            name?: string;
            /** @example 09123456789 */
            phone?: Record<string, never> | null;
            /** @example No. 1, Main Road */
            address?: Record<string, never> | null;
            /** @example Deliver before 6pm */
            notes?: Record<string, never>;
            /** @example VIBER */
            channelType?: components["schemas"]["ShopChannelType"];
            /** @example YangonCentralShop */
            channelName?: string;
        };
        CustomerResponseDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            id: string;
            /** @example Aung Aung */
            name: string;
            /** @example 09123456789 */
            phone?: Record<string, never> | null;
            /** @example No. 1, Main Road */
            address?: Record<string, never> | null;
            /** @example Prefers morning delivery */
            notes?: Record<string, never> | null;
            /** @example 2026-09-18T10:00:00.000Z */
            createdAt: string;
            /** @example 2026-09-18T10:00:00.000Z */
            updatedAt: string;
        };
        CustomerListMetaDto: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            perPage: number;
            /** @example 1 */
            total: number;
            /** @example 1 */
            totalPages: number;
        };
        CustomerListResponseDto: {
            data: components["schemas"]["CustomerResponseDto"][];
            meta: components["schemas"]["CustomerListMetaDto"];
        };
        CreateCustomerDto: {
            /** @example Aung Aung */
            name: string;
            /** @example 09123456789 */
            phone?: Record<string, never> | null;
            /** @example No. 1, Main Road */
            address?: Record<string, never> | null;
            /** @example Prefers morning delivery */
            notes?: Record<string, never> | null;
        };
        UpdateCustomerDto: {
            /** @example Aung Aung */
            name?: string;
            /** @example 09123456789 */
            phone?: Record<string, never> | null;
            /** @example No. 1, Main Road */
            address?: Record<string, never> | null;
            /** @example Prefers morning delivery */
            notes?: Record<string, never> | null;
        };
        /** @enum {string} */
        RiderVehicleType: "BIKE" | "MOTORBIKE" | "CAR" | "OTHER";
        RiderResponseDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            id: string;
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            userId: string;
            /** @example John Rider */
            name: string;
            /** @example john.rider@delivery.local */
            email: string;
            /** @example 09123456789 */
            phone?: Record<string, never> | null;
            status: components["schemas"]["UserStatus"];
            /** @example BIKE */
            vehicleType: components["schemas"]["RiderVehicleType"];
            /** @example MDY-1234 */
            vehiclePlate?: Record<string, never> | null;
            /** @example DL-2024-99812 */
            licenseNo?: Record<string, never> | null;
            /** @example 09987654321 */
            nrcNumber?: Record<string, never> | null;
            /** @example 09111111111 */
            emergencyContactPhone?: Record<string, never> | null;
            /** @example Prefers north townships */
            notes?: Record<string, never> | null;
            /** @description Township ids this rider serves */
            townshipIds: string[];
            /** @example 2026-09-18T10:00:00.000Z */
            createdAt: string;
            /** @example 2026-09-18T10:00:00.000Z */
            updatedAt: string;
        };
        RiderListMetaDto: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            perPage: number;
            /** @example 1 */
            total: number;
            /** @example 1 */
            totalPages: number;
        };
        RiderListResponseDto: {
            data: components["schemas"]["RiderResponseDto"][];
            meta: components["schemas"]["RiderListMetaDto"];
        };
        CreateRiderDto: {
            /** @example John Rider */
            name: string;
            /** @example john.rider@delivery.local */
            email: string;
            /** @example 09123456789 */
            phone?: Record<string, never> | null;
            /** @example StrongP@ssw0rd */
            password: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
            /** @default BIKE */
            vehicleType: components["schemas"]["RiderVehicleType"];
            /** @example MDY-1234 */
            vehiclePlate?: Record<string, never> | null;
            /** @example DL-2024-99812 */
            licenseNo?: Record<string, never> | null;
            /** @example 09987654321 */
            nrcNumber?: Record<string, never> | null;
            /** @example 09111111111 */
            emergencyContactPhone?: Record<string, never> | null;
            /** @example Prefers north townships */
            notes?: Record<string, never> | null;
            /** @description Townships this rider serves */
            townshipIds?: string[];
        };
        UpdateRiderDto: {
            /** @example John Rider Updated */
            name?: string;
            /** @example john.updated@delivery.local */
            email?: string;
            /** @example 09876543210 */
            phone?: Record<string, never> | null;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE";
            /** @description Reset rider password */
            password?: string;
            vehicleType?: components["schemas"]["RiderVehicleType"];
            /** @example MDY-1234 */
            vehiclePlate?: Record<string, never> | null;
            /** @example DL-2024-99812 */
            licenseNo?: Record<string, never> | null;
            /** @example 09987654321 */
            nrcNumber?: Record<string, never> | null;
            /** @example 09111111111 */
            emergencyContactPhone?: Record<string, never> | null;
            /** @example Prefers north townships */
            notes?: Record<string, never> | null;
            /** @description Replace township coverage */
            townshipIds?: string[];
        };
        /** @enum {string} */
        OrderStatus: "ASSIGNED" | "DELIVERED" | "FAILED";
        OrderResponseDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            id: string;
            /** @example ORD-01J8ZQ4C7M3W9X2K5T8R1V6B0P */
            trackingCode: string;
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            shopId: string;
            /** @example Township Shop */
            shopName: string;
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            customerId: string;
            /** @example Township Customer */
            customerName: string;
            /** @example 09123456789 */
            customerPhone?: Record<string, never> | null;
            /** @example No. 12 Main Road */
            customerAddress?: Record<string, never> | null;
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            townshipId: string;
            /** @example Hlaing */
            townshipName: string;
            riderId?: Record<string, never> | null;
            riderName?: Record<string, never> | null;
            riderPhone?: Record<string, never> | null;
            /** @description Opaque package metadata; shape and physical units are not yet defined */
            packageInfo?: Record<string, never> | null;
            /**
             * @description Decimal string
             * @example 0.00
             */
            deliveryFee: string;
            /**
             * @description Decimal string
             * @example 0.00
             */
            codAmount: string;
            status: components["schemas"]["OrderStatus"];
            notes?: Record<string, never> | null;
            /** @example 2026-09-18T10:00:00.000Z */
            createdAt: string;
            /** @example 2026-09-18T10:00:00.000Z */
            updatedAt: string;
        };
        OrderListMetaDto: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            perPage: number;
            /** @example 1 */
            total: number;
            /** @example 1 */
            totalPages: number;
        };
        OrderListResponseDto: {
            data: components["schemas"]["OrderResponseDto"][];
            meta: components["schemas"]["OrderListMetaDto"];
        };
        CreateOrderDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            townshipId: string;
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            shopId: string;
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            customerId: string;
            /** @description Opaque package metadata; shape and physical units are not yet defined */
            packageInfo?: Record<string, never> | null;
            /**
             * @default 0
             * @example 0.00
             */
            deliveryFee: string;
            /**
             * @default 0
             * @example 0.00
             */
            codAmount: string;
            notes?: Record<string, never> | null;
        };
        OrderHistoryResponseDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            id: string;
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            orderId: string;
            fromStatus?: components["schemas"]["OrderStatus"] | null;
            toStatus: components["schemas"]["OrderStatus"];
            changedBy?: Record<string, never> | null;
            note?: Record<string, never> | null;
            /** @example 2026-09-18T10:00:00.000Z */
            createdAt: string;
        };
        OrderDetailResponseDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            id: string;
            /** @example ORD-01J8ZQ4C7M3W9X2K5T8R1V6B0P */
            trackingCode: string;
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            shopId: string;
            /** @example Township Shop */
            shopName: string;
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            customerId: string;
            /** @example Township Customer */
            customerName: string;
            /** @example 09123456789 */
            customerPhone?: Record<string, never> | null;
            /** @example No. 12 Main Road */
            customerAddress?: Record<string, never> | null;
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            townshipId: string;
            /** @example Hlaing */
            townshipName: string;
            riderId?: Record<string, never> | null;
            riderName?: Record<string, never> | null;
            riderPhone?: Record<string, never> | null;
            /** @description Opaque package metadata; shape and physical units are not yet defined */
            packageInfo?: Record<string, never> | null;
            /**
             * @description Decimal string
             * @example 0.00
             */
            deliveryFee: string;
            /**
             * @description Decimal string
             * @example 0.00
             */
            codAmount: string;
            status: components["schemas"]["OrderStatus"];
            notes?: Record<string, never> | null;
            /** @example 2026-09-18T10:00:00.000Z */
            createdAt: string;
            /** @example 2026-09-18T10:00:00.000Z */
            updatedAt: string;
            history: components["schemas"]["OrderHistoryResponseDto"][];
        };
        TownshipResponseDto: {
            id: string;
            /** @example Hlaing */
            name: string;
            /** @description Whether an ACTIVE rider is assigned to this township */
            selectable: boolean;
            createdAt: string;
            updatedAt: string;
        };
        CreateTownshipDto: {
            /** @example Hlaing */
            name: string;
        };
        UpdateTownshipDto: {
            /** @example Hlaing */
            name?: string;
        };
        AssignDeliveryDto: {
            riderId: string;
        };
        /** @enum {string} */
        DeliveryStatus: "ASSIGNED" | "DELIVERED" | "FAILED";
        /** @enum {string} */
        FailureReason: "CUSTOMER_UNAVAILABLE" | "WRONG_ADDRESS" | "CUSTOMER_REFUSED" | "CUSTOMER_RESCHEDULED" | "DAMAGED_PACKAGE" | "OTHER";
        /** @enum {string} */
        DeliveryHistoryEvent: "ASSIGNED" | "REASSIGNED" | "DELIVERED" | "FAILED" | "RETRY_CREATED";
        DeliveryHistoryResponseDto: {
            id: string;
            deliveryAttemptId: string;
            event: components["schemas"]["DeliveryHistoryEvent"];
            actorId?: Record<string, never> | null;
            previousRiderId?: Record<string, never> | null;
            newRiderId?: Record<string, never> | null;
            note?: Record<string, never> | null;
            createdAt: string;
        };
        DeliveryDetailResponseDto: {
            id: string;
            orderId: string;
            riderId: string;
            attemptNumber: number;
            status: components["schemas"]["DeliveryStatus"];
            failureReason?: components["schemas"]["FailureReason"] | null;
            failureNote?: Record<string, never> | null;
            assignedBy?: Record<string, never> | null;
            assignedAt: string;
            deliveredAt?: Record<string, never> | null;
            failedAt?: Record<string, never> | null;
            createdAt: string;
            updatedAt: string;
            history: components["schemas"]["DeliveryHistoryResponseDto"][];
        };
        FailDeliveryDto: {
            reason: components["schemas"]["FailureReason"];
            note?: Record<string, never> | null;
        };
        DeliveryResponseDto: {
            id: string;
            orderId: string;
            riderId: string;
            attemptNumber: number;
            status: components["schemas"]["DeliveryStatus"];
            failureReason?: components["schemas"]["FailureReason"] | null;
            failureNote?: Record<string, never> | null;
            assignedBy?: Record<string, never> | null;
            assignedAt: string;
            deliveredAt?: Record<string, never> | null;
            failedAt?: Record<string, never> | null;
            createdAt: string;
            updatedAt: string;
        };
        DeliveryListResponseDto: {
            data: components["schemas"]["DeliveryResponseDto"][];
        };
        RetryDeliveryDto: {
            riderId: string;
        };
        RiderBoardOrderDto: {
            id: string;
            trackingCode: string;
            status: components["schemas"]["OrderStatus"];
            townshipId: string;
            townshipName: string;
            shopName: string;
            assignedRiderName?: Record<string, never> | null;
            deliveryAttemptId?: string;
            attemptNumber?: number;
            isMine: boolean;
            createdAt: string;
            customerId?: string | null;
            customerName?: string | null;
            customerPhone?: Record<string, never> | null;
            customerAddress?: Record<string, never> | null;
            packageInfo?: Record<string, never> | null;
            /** @example 0.00 */
            deliveryFee?: string;
            /** @example 0.00 */
            codAmount?: string;
            notes?: Record<string, never> | null;
        };
        RiderBoardMetaDto: {
            page: number;
            perPage: number;
            total: number;
            totalPages: number;
        };
        RiderBoardResponseDto: {
            /** @example 2026-09-29 */
            date: string;
            /** @enum {string} */
            filter: "mine" | "all";
            data: components["schemas"]["RiderBoardOrderDto"][];
            meta: components["schemas"]["RiderBoardMetaDto"];
        };
        RiderDashboardResponseDto: {
            /** @example 2026-09-29 */
            date: string;
            /** @description Assigned attempts in the date cohort that remain open */
            assigned: number;
            delivered: number;
            failed: number;
            /** @description Percentage from 0 to 100; zero when there are no completed attempts */
            successRate: number;
            /** @example 12000.00 */
            codCollected: string;
            /** @example 45000.00 */
            codOutstanding: string;
        };
        OfficeDashboardSummaryDto: {
            /** @example 24 */
            ordersCreated: number;
            /**
             * @description Current assigned orders, across all dates
             * @example 8
             */
            openAssignments: number;
            /** @example 12 */
            delivered: number;
            /** @example 2 */
            failed: number;
            /**
             * @description Percent of completed attempts delivered on the selected date
             * @example 85.71
             */
            successRate: number;
        };
        OfficeDashboardOpenWorkDto: {
            riderId: string;
            riderName: string;
            townshipId: string;
            townshipName: string;
            /** @example 4 */
            count: number;
        };
        OfficeDashboardActivityDto: {
            id: string;
            orderId: string;
            trackingCode: string;
            townshipName: string;
            riderName: Record<string, never> | null;
            previousRiderName: Record<string, never> | null;
            event: components["schemas"]["DeliveryHistoryEvent"];
            createdAt: string;
        };
        OfficeDashboardFailedOrderDto: {
            orderId: string;
            trackingCode: string;
            townshipName: string;
            riderName: Record<string, never> | null;
            attemptNumber: number;
            failedAt: string;
        };
        OfficeDashboardResponseDto: {
            /** @example 2026-10-03 */
            date: string;
            summary: components["schemas"]["OfficeDashboardSummaryDto"];
            openWork: components["schemas"]["OfficeDashboardOpenWorkDto"][];
            recentActivity: components["schemas"]["OfficeDashboardActivityDto"][];
            failedOrders: components["schemas"]["OfficeDashboardFailedOrderDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
        };
    };
    AuthController_login_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    AuthController_me_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponseDto"];
                };
            };
        };
    };
    AuthController_changePassword_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_list_v1: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
                /** @description Search by name, email or phone */
                search?: string;
                /** @description Filter by role id */
                roleId?: string;
                status?: components["schemas"]["UserStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponseDto"];
                };
            };
        };
    };
    UsersController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UsersController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UsersController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    PermissionsController_catalog_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionGroupDto"][];
                };
            };
        };
    };
    PermissionsController_grants_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Granted permission keys */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    PermissionsController_replaceGrants_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRolePermissionsDto"];
            };
        };
        responses: {
            /** @description The granted keys after the update */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    RolesController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponseDto"][];
                };
            };
        };
    };
    RolesController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRoleResponseDto"];
                };
            };
        };
    };
    RolesController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponseDto"];
                };
            };
        };
    };
    RolesController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateRoleResponseDto"];
                };
            };
        };
    };
    ShopsController_list_v1: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
                /** @description Search by shop name, phone or address */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopListResponseDto"];
                };
            };
        };
    };
    ShopsController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShopDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopResponseDto"];
                };
            };
        };
    };
    ShopsController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopResponseDto"];
                };
            };
        };
    };
    ShopsController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ShopsController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateShopDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopResponseDto"];
                };
            };
        };
    };
    CustomersController_list_v1: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
                /** @description Search by customer name, phone or address */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerListResponseDto"];
                };
            };
        };
    };
    CustomersController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCustomerDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerResponseDto"];
                };
            };
        };
    };
    CustomersController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerResponseDto"];
                };
            };
        };
    };
    CustomersController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CustomersController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCustomerDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerResponseDto"];
                };
            };
        };
    };
    RidersController_list_v1: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
                /** @description Search by rider name, email or phone */
                search?: string;
                status?: components["schemas"]["UserStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiderListResponseDto"];
                };
            };
        };
    };
    RidersController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRiderDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiderResponseDto"];
                };
            };
        };
    };
    RidersController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiderResponseDto"];
                };
            };
        };
    };
    RidersController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RidersController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRiderDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiderResponseDto"];
                };
            };
        };
    };
    OrdersController_list_v1: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
                /** @description Search by tracking code, customer name, or customer phone */
                search?: string;
                status?: components["schemas"]["OrderStatus"];
                /** @description Filter by shop id */
                shopId?: string;
                /** @description Filter by customer id */
                customerId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderListResponseDto"];
                };
            };
        };
    };
    OrdersController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponseDto"];
                };
            };
        };
    };
    OrdersController_history_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderHistoryResponseDto"][];
                };
            };
        };
    };
    OrdersController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailResponseDto"];
                };
            };
        };
    };
    TownshipsController_list_v1: {
        parameters: {
            query?: {
                /** @description Only return townships with an active rider */
                selectable?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TownshipResponseDto"][];
                };
            };
        };
    };
    TownshipsController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTownshipDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TownshipResponseDto"];
                };
            };
        };
    };
    TownshipsController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTownshipDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TownshipResponseDto"];
                };
            };
        };
    };
    DeliveriesController_assign_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignDeliveryDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryDetailResponseDto"];
                };
            };
        };
    };
    DeliveriesController_reassign_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignDeliveryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryDetailResponseDto"];
                };
            };
        };
    };
    DeliveriesController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryDetailResponseDto"];
                };
            };
        };
    };
    DeliveriesController_complete_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryDetailResponseDto"];
                };
            };
        };
    };
    DeliveriesController_fail_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FailDeliveryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryDetailResponseDto"];
                };
            };
        };
    };
    OrdersDeliveriesController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryListResponseDto"];
                };
            };
        };
    };
    OrdersDeliveriesController_retry_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryDeliveryDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryDetailResponseDto"];
                };
            };
        };
    };
    RiderDeliveriesController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryListResponseDto"];
                };
            };
        };
    };
    RiderBoardController_board_v1: {
        parameters: {
            query?: {
                /** @description Office-local calendar date; defaults to today */
                date?: string;
                filter?: "mine" | "all";
                page?: number;
                perPage?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiderBoardResponseDto"];
                };
            };
        };
    };
    RiderBoardController_dashboard_v1: {
        parameters: {
            query?: {
                /** @description Office-local calendar date; defaults to today */
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiderDashboardResponseDto"];
                };
            };
        };
    };
    OfficeDashboardController_getDashboard_v1: {
        parameters: {
            query?: {
                /** @description Office-local calendar date; defaults to today */
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfficeDashboardResponseDto"];
                };
            };
        };
    };
}
