/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange credentials for an access token */
        post: operations["AuthController_login_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user profile + permissions */
        get: operations["AuthController_me_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the authenticated user password */
        post: operations["AuthController_changePassword_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users with search, filters and pagination */
        get: operations["UsersController_list_v1"];
        put?: never;
        /** Create a new user */
        post: operations["UsersController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user by id */
        get: operations["UsersController_get_v1"];
        put?: never;
        post?: never;
        /** Delete a user */
        delete: operations["UsersController_remove_v1"];
        options?: never;
        head?: never;
        /** Update a user */
        patch: operations["UsersController_update_v1"];
        trace?: never;
    };
    "/api/v1/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the fixed permission catalog grouped by module */
        get: operations["PermissionsController_catalog_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/permissions/roles/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the permission keys granted to a role */
        get: operations["PermissionsController_grants_v1"];
        /** Replace the permission set granted to a role */
        put: operations["PermissionsController_replaceGrants_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List roles with user counts */
        get: operations["RolesController_list_v1"];
        put?: never;
        /** Create a role */
        post: operations["RolesController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a role by id */
        get: operations["RolesController_get_v1"];
        put?: never;
        post?: never;
        /** Delete a role (blocked if assigned) */
        delete: operations["RolesController_remove_v1"];
        options?: never;
        head?: never;
        /** Edit a role description */
        patch: operations["RolesController_update_v1"];
        trace?: never;
    };
    "/api/v1/shops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List shops with search, filters and pagination */
        get: operations["ShopsController_list_v1"];
        put?: never;
        /** Create a new shop */
        post: operations["ShopsController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shops/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a shop by id */
        get: operations["ShopsController_get_v1"];
        put?: never;
        post?: never;
        /** Delete a shop */
        delete: operations["ShopsController_remove_v1"];
        options?: never;
        head?: never;
        /** Update a shop */
        patch: operations["ShopsController_update_v1"];
        trace?: never;
    };
    "/api/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List customers with search and pagination */
        get: operations["CustomersController_list_v1"];
        put?: never;
        /** Create a new customer */
        post: operations["CustomersController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a customer by id */
        get: operations["CustomersController_get_v1"];
        put?: never;
        post?: never;
        /** Delete a customer */
        delete: operations["CustomersController_remove_v1"];
        options?: never;
        head?: never;
        /** Update a customer */
        patch: operations["CustomersController_update_v1"];
        trace?: never;
    };
    "/api/v1/riders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List riders with search, filters and pagination */
        get: operations["RidersController_list_v1"];
        put?: never;
        /** Create a rider — creates a RIDER-role user row and the rider profile in one transaction */
        post: operations["RidersController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/riders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a rider by id (id = the backing user id) */
        get: operations["RidersController_get_v1"];
        put?: never;
        post?: never;
        /** Delete a rider and its backing user row */
        delete: operations["RidersController_remove_v1"];
        options?: never;
        head?: never;
        /** Update rider profile and/or whitelisted user fields (name, phone, status) */
        patch: operations["RidersController_update_v1"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponseDto: {
            /**
             * @example ok
             * @enum {string}
             */
            status: "ok" | "error";
            /** @example 2026-09-14T10:00:00.000Z */
            timestamp: string;
            /** @example 1234.56 */
            uptime: number;
            /**
             * @example {
             *       "database": {
             *         "status": "up",
             *         "latencyMs": 3
             *       }
             *     }
             */
            dependencies: Record<string, never>;
        };
        LoginDto: {
            /** @example owner@mail.com */
            email: string;
            /** @example Password1234 */
            password: string;
        };
        /** @enum {string} */
        UserStatus: "ACTIVE" | "INACTIVE";
        UserResponseDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            id: string;
            /** @example System Owner */
            name: string;
            /** @example owner@mail.com */
            email: string;
            /** @example 09123456789 */
            phone: Record<string, never> | null;
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            roleId: string;
            /** @example OWNER */
            role: string;
            /** @example ACTIVE */
            status: components["schemas"]["UserStatus"];
            /** @example 2026-09-14T10:00:00.000Z */
            createdAt: string;
            /** @example 2026-09-14T10:00:00.000Z */
            updatedAt: string;
        };
        LoginResponseDto: {
            /** @description JWT access token */
            accessToken: string;
            /** @description Authenticated user */
            user: components["schemas"]["UserResponseDto"];
            /** @description Effective permission keys for the user role */
            permissions: string[];
        };
        MeResponseDto: {
            /** @description Authenticated user profile */
            user: components["schemas"]["UserResponseDto"];
            /** @description Effective permission keys for the user role */
            permissions: string[];
        };
        ChangePasswordDto: {
            currentPassword: string;
            newPassword: string;
        };
        PaginationMetaDto: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            perPage: number;
            /** @example 42 */
            total: number;
            /** @example 3 */
            totalPages: number;
        };
        UserListResponseDto: {
            data: components["schemas"]["UserResponseDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        CreateUserDto: {
            /** @example John Rider */
            name: string;
            /** @example john@delivery.local */
            email: string;
            /** @example 09123456789 */
            phone?: Record<string, never> | null;
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            roleId: string;
            /** @example StrongP@ssw0rd */
            password: string;
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
        };
        UpdateUserDto: {
            /** @example John Rider Updated */
            name?: string;
            /** @example john.updated@delivery.local */
            email?: string;
            /** @example 09876543210 */
            phone?: Record<string, never> | null;
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            roleId?: string;
            status?: components["schemas"]["UserStatus"];
            /** @description Reset user password (min 8 characters) */
            password?: string;
        };
        PermissionGroupDto: {
            /** @example users */
            module: string;
            /**
             * @example [
             *       "users.create",
             *       "users.read"
             *     ]
             */
            permissions: string[];
        };
        UpdateRolePermissionsDto: {
            /**
             * @description Permission keys to grant (replaces the set)
             * @example [
             *       "users.create",
             *       "users.read"
             *     ]
             */
            permissions: string[];
        };
        RoleResponseDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            id: string;
            /** @example MANAGER */
            name: string;
            /** @example Floor manager */
            description: Record<string, never> | null;
            /** @example false */
            isSystem: boolean;
            /** @example 3 */
            userCount: number;
        };
        CreateRoleDto: {
            /**
             * @description Uppercase role name, 2-32 chars, letters/digits/underscore
             * @example MANAGER
             */
            name: string;
            /** @example Operations manager */
            description?: Record<string, never>;
        };
        CreateRoleResponseDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            id: string;
            /** @example MANAGER */
            name: string;
            /** @example false */
            isSystem: boolean;
        };
        UpdateRoleDto: {
            /** @example Operations manager */
            description?: Record<string, never>;
        };
        UpdateRoleResponseDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            id: string;
        };
        /** @enum {string} */
        ShopChannelType: "VIBER" | "TELEGRAM";
        ShopResponseDto: {
            /** @example 3fa85f64-5717-4562-b3fc-2c963f66afa6 */
            id: string;
            /** @example Yangon Fresh Market */
            name: string;
            /** @example 09123456789 */
            phone: Record<string, never> | null;
            /** @example No. 12, Bogyoke Road, Yangon */
            address: Record<string, never> | null;
            /** @example Preferred delivery contact: shop manager */
            notes: Record<string, never> | null;
            channelType: components["schemas"]["ShopChannelType"];
            /** @example Yangon Fresh Market Group */
            channelName: string;
            /** @example 2026-09-17T10:00:00.000Z */
            createdAt: string;
            /** @example 2026-09-17T10:00:00.000Z */
            updatedAt: string;
        };
        ShopListResponseDto: {
            data: components["schemas"]["ShopResponseDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        CreateShopDto: {
            /** @example Yangon Fresh Market */
            name: string;
            /** @example 09123456789 */
            phone?: Record<string, never> | null;
            /** @example No. 12, Bogyoke Road, Yangon */
            address: Record<string, never> | null;
            /** @example Preferred delivery contact: shop manager */
            notes: Record<string, never> | null;
            channelType: components["schemas"]["ShopChannelType"];
            /** @example Yangon Fresh Market Group */
            channelName: string;
        };
        UpdateShopDto: {
            /** @example Yangon Fresh Market Updated */
            name?: string;
            /** @example 09876543210 */
            phone?: Record<string, never> | null;
            /** @example No. 34, Merchant Street, Yangon */
            address?: Record<string, never> | null;
            /** @example Updated points of contact */
            notes?: Record<string, never> | null;
            channelType?: components["schemas"]["ShopChannelType"];
            /** @example Yangon Fresh Market Group */
            channelName?: string;
        };
        CustomerResponseDto: {
            /** Format: uuid */
            id: string;
            name: string;
            phone?: Record<string, never>;
            address?: Record<string, never>;
            notes?: Record<string, never>;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CustomerListResponseDto: {
            data: components["schemas"]["CustomerResponseDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        CreateCustomerDto: {
            /** @description Customer full name */
            name: string;
            phone?: string;
            address?: string;
            notes?: string;
        };
        UpdateCustomerDto: {
            /** @description Customer full name */
            name?: string;
            phone?: string;
            address?: string;
            notes?: string;
        };
        /** @enum {string} */
        RiderVehicleType: "BIKE" | "MOTORBIKE" | "CAR" | "OTHER";
        RiderUserDto: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            phone: Record<string, never> | null;
            /**
             * @description UserStatus enum value
             * @example ACTIVE
             */
            status: string;
        };
        RiderResponseDto: {
            /**
             * Format: uuid
             * @description Rider id (same as the user id)
             */
            userId: string;
            licenseNo: Record<string, never> | null;
            /** @default BIKE */
            vehicleType: components["schemas"]["RiderVehicleType"];
            vehiclePlate: Record<string, never> | null;
            nrcNumber: Record<string, never> | null;
            emergencyContactPhone: Record<string, never> | null;
            isAvailable: boolean;
            notes: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            user: components["schemas"]["RiderUserDto"];
        };
        RiderListResponseDto: {
            data: components["schemas"]["RiderResponseDto"][];
            meta: components["schemas"]["PaginationMetaDto"];
        };
        CreateRiderDto: {
            /** @description Rider full name */
            name: string;
            /** Format: email */
            email: string;
            password: string;
            phone?: string;
            /**
             * @description User status of the backing user row
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
            /** @description Driving license number */
            licenseNo?: string;
            /**
             * @default BIKE
             * @enum {string}
             */
            vehicleType: "BIKE" | "MOTORBIKE" | "CAR" | "OTHER";
            /** @description Vehicle plate number */
            vehiclePlate?: string;
            /** @description National Registration Card number */
            nrcNumber?: string;
            /** @description Emergency contact phone number */
            emergencyContactPhone?: string;
            /**
             * @description Whether the rider is currently available for deliveries
             * @default true
             */
            isAvailable: boolean;
            notes?: string;
        };
        UpdateRiderDto: {
            name?: string;
            phone?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE";
            licenseNo?: string;
            /** @enum {string} */
            vehicleType?: "BIKE" | "MOTORBIKE" | "CAR" | "OTHER";
            vehiclePlate?: string;
            nrcNumber?: string;
            emergencyContactPhone?: string;
            isAvailable?: boolean;
            notes?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
        };
    };
    AuthController_login_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
        };
    };
    AuthController_me_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponseDto"];
                };
            };
        };
    };
    AuthController_changePassword_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_list_v1: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
                /** @description Search by name, email or phone */
                search?: string;
                /** @description Filter by role id */
                roleId?: string;
                status?: components["schemas"]["UserStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponseDto"];
                };
            };
        };
    };
    UsersController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UsersController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    UsersController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
        };
    };
    PermissionsController_catalog_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionGroupDto"][];
                };
            };
        };
    };
    PermissionsController_grants_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Granted permission keys */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    PermissionsController_replaceGrants_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRolePermissionsDto"];
            };
        };
        responses: {
            /** @description The granted keys after the update */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    RolesController_list_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponseDto"][];
                };
            };
        };
    };
    RolesController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRoleResponseDto"];
                };
            };
        };
    };
    RolesController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleResponseDto"];
                };
            };
        };
    };
    RolesController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateRoleResponseDto"];
                };
            };
        };
    };
    ShopsController_list_v1: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
                /** @description Search by name, phone or channel name */
                search?: string;
                channelType?: components["schemas"]["ShopChannelType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopListResponseDto"];
                };
            };
        };
    };
    ShopsController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShopDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopResponseDto"];
                };
            };
        };
    };
    ShopsController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopResponseDto"];
                };
            };
        };
    };
    ShopsController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ShopsController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateShopDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopResponseDto"];
                };
            };
        };
    };
    CustomersController_list_v1: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
                /** @description Search by name or phone */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerListResponseDto"];
                };
            };
        };
    };
    CustomersController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCustomerDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerResponseDto"];
                };
            };
        };
    };
    CustomersController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerResponseDto"];
                };
            };
        };
    };
    CustomersController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CustomersController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCustomerDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerResponseDto"];
                };
            };
        };
    };
    RidersController_list_v1: {
        parameters: {
            query?: {
                page?: number;
                perPage?: number;
                /** @description Search by rider name, email or phone (on the user row) */
                search?: string;
                /** @description Filter by vehicle type */
                vehicleType?: string;
                /** @description Filter by availability */
                isAvailable?: boolean;
                /** @description Filter by user status */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiderListResponseDto"];
                };
            };
        };
    };
    RidersController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRiderDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiderResponseDto"];
                };
            };
        };
    };
    RidersController_get_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiderResponseDto"];
                };
            };
        };
    };
    RidersController_remove_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RidersController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRiderDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiderResponseDto"];
                };
            };
        };
    };
}
